name: bidrag-beregn-barnebidrag-rest
ingresses:
  - https://bidrag-beregn-barnebidrag-rest.intern.nav.no
azure_access_inbound:
  - application: bidrag-cucumber-cloud
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-simuler-beregning
    namespace: bidrag
    cluster: prod-gcp
unsecured:
  bidragsjablon_url: bidrag-sjablon.prod-fss-pub.nais.io
  bidragsjablon_scope: prod-fss.bidrag.bidrag-sjablon
