SJABLON_URL: https://bidrag-sjablon-q1.nais.preprod.local/bidrag-sjablon

server:
  servlet:
    context-path: /bidrag-beregn-barnebidrag-rest
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# Profil for lokal kjøring
spring.profiles: local

# Lokal profil bruker selvstendige wiremocks
wiremock.server:
  files: classpath:/__files
  stubs: classpath:/wiremock_stubs

