apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-beregn-bidrag-rest
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  liveness:
    path: /bidrag-beregn-bidrag-rest/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-beregn-bidrag-rest/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-beregn-bidrag-rest/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress_preprod }}
    - {{ ingress_nais }}
  vault:
    enabled: false
  env:
    - name: BIDRAGSEVNE_URL
      value: {{ bidragsevneurl }}
    - name: SJABLON_URL
      value: {{ sjablonurl }}
